const availableQuestion = [
  {
    value: 'blinx',
    show: true,
    name: 'FriendlyNameBlinx',
    boards: ['esp32c3'],
    description: 'The name of the blinx',
    type: 'string',
  },

  {
    value: '300',
    show: true,
    name: 'SIZE_BUFFER_50MS',
    boards: ['esp32c3'],
    description: 'The size of the buffer of the 50ms',
    type: 'int',
  },
  {
    value: '300',
    show: true,
    name: 'SIZE_BUFFER_1S',
    boards: ['esp32c3'],
    description: 'The size of the buffer of the 1s',
    type: 'int',
  },
  {
    value: '300',
    show: true,
    name: 'SIZE_BUFFER_10S',
    boards: ['esp32c3'],
    description: 'The size of the buffer of the 10s',
    type: 'int',
  },
  {
    value: '300',
    show: true,
    name: 'SIZE_BUFFER_1M',
    boards: ['esp32c3'],
    description: 'The size of the buffer of the 1m',
    type: 'int',
  },
  {
    value: '300',
    show: true,
    name: 'SIZE_BUFFER_10M',
    boards: ['esp32c3'],
    description: 'The size of the buffer of the 10m',
    type: 'int',
  },
  {
    value: '300',
    show: true,
    name: 'SIZE_BUFFER_1H',
    boards: ['esp32c3'],
    description: 'The size of the buffer of the 1h',
    type: 'int',
  },

  {
    value: '300',
    show: true,
    name: 'SIZE_BUFFER_50MS_Tampon',
    boards: ['esp32c3'],
    description: 'The size of the tampon of the 50ms',
    type: 'int',
  },
  {
    value: '300',
    show: true,
    name: 'SIZE_BUFFER_1S_Tampon',
    boards: ['esp32c3'],
    description: 'The size of the tampon of the 1s',
    type: 'int',
  },
  {
    value: '300',
    show: true,
    name: 'SIZE_BUFFER_10S_Tampon',
    boards: ['esp32c3'],
    description: 'The size of the tampon of the 10s',
    type: 'int',
  },
  {
    value: '300',
    show: true,
    name: 'SIZE_BUFFER_1M_Tampon',
    boards: ['esp32c3'],
    description: 'The size of the tampon of the 1m',
    type: 'int',
  },
  {
    value: '300',
    show: true,
    name: 'SIZE_BUFFER_10M_Tampon',
    boards: ['esp32c3'],
    description: 'The size of the tampon of the 10m',
    type: 'int',
  },
  {
    value: '300',
    show: true,
    name: 'SIZE_BUFFER_1H_Tampon',
    boards: ['esp32c3'],
    description: 'The size of the tampon of the 1h',
    type: 'int',
  },

  {
    value: '300',
    show: true,
    name: 'SIZE_BUFFER_50MS_limit',
    boards: ['esp32c3'],
    description: 'How many data can we loose for 50ms',
    type: 'int',
  },
  {
    value: '300',
    show: true,
    name: 'SIZE_BUFFER_1S_limit',
    boards: ['esp32c3'],
    description: 'How many data can we loose for 1s',
    type: 'int',
  },
  {
    value: '300',
    show: true,
    name: 'SIZE_BUFFER_10S_limit',
    boards: ['esp32c3'],
    description: 'How many data can we loose for 10s',
    type: 'int',
  },
  {
    value: '300',
    show: true,
    name: 'SIZE_BUFFER_1M_limit',
    boards: ['esp32c3'],
    description: 'How many data can we loose for 1m',
    type: 'int',
  },
  {
    value: '300',
    show: true,
    name: 'SIZE_BUFFER_10M_limit',
    boards: ['esp32c3'],
    description: 'How many data can we loose for 10m',
    type: 'int',
  },
  {
    value: '300',
    show: true,
    name: 'SIZE_BUFFER_1H_limit',
    boards: ['esp32c3'],
    description: 'How many data can we loose for 1h'
  }
];
  
  export default availableQuestion;
  